#!/bin/bash

# Utility function to update cartridge configuration

function update-configuration {
    # Native installations of python
    echo "$OPENSHIFT_PYTHONNODEJS_DIR/virtenv/bin:$OPENSHIFT_PYTHONNODEJS_DIR/bin" > $OPENSHIFT_PYTHONNODEJS_DIR/env/OPENSHIFT_PYTHONNODEJS_PATH_ELEMENT
    echo "$OPENSHIFT_PYTHONNODEJS_DIR/virtenv" > $OPENSHIFT_PYTHONNODEJS_DIR/env/VIRTUAL_ENV
}
