#!/bin/bash

# Utility function to create virtual environments

function relative-virtenv {
    # Clean the lib64->lib symlink
    virtualenv --quiet --never-download --relocatable $OPENSHIFT_PYTHONNODEJS_DIR/virtenv
    # symlinks -r -c -s $OPENSHIFT_PYTHONNODEJS_DIR/virtenv >/dev/null
}

function create-virtenv {
    # Initialize the virtual environment
    mkdir -p $OPENSHIFT_PYTHONNODEJS_DIR/virtenv/bin
    mkdir -p $OPENSHIFT_PYTHONNODEJS_DIR/virtenv/.python-eggs/
    virtualenv --quiet --never-download --system-site-packages $OPENSHIFT_PYTHONNODEJS_DIR/virtenv

    # Bug 995284
    versions=( $(python -c 'import sys; print "%d %d.%d" % (sys.version_info[0], sys.version_info[0], sys.version_info[1])') )
    for vers in "${versions[@]}"; do
        [ -L $OPENSHIFT_PYTHONNODEJS_DIR/virtenv/bin/python$vers ] || ln -s python $OPENSHIFT_PYTHONNODEJS_DIR/virtenv/bin/python$vers
    done

    relative-virtenv
}

function activate-virtenv {
    source $OPENSHIFT_PYTHONNODEJS_DIR/virtenv/bin/activate
}
